spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:33060/smart-lab?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: homestead
    password: secret
    schema:
      - classpath:database/schema.sql
      - classpath:database/schema_oauth.sql
      - classpath:database/schema_acl.sql
    data:
      - classpath:database/data.sql
      - classpath:database/data_oauth.sql
      - classpath:database/data_acl.sql
    initialization-mode: always
#    continue-on-error: true

server:
  port: 8088
mybatis:
  type-handlers-package: cn.chingshen.smartlab.typehandlers

