spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:33060/smart-lab?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: homestead
    password: secret
    schema: classpath:database/schema.sql
    data: classpath:database/data.sql
    initialization-mode: always

server:
  port: 8001
mybatis:
  type-handlers-package: cn.chingshen.smartlab.typehandlers
